### ISSUE TITLE
请求加入telegram消息推送

### ISSUE THREAD

**Issue by ChirmyRam** [xhuanya/euserv_renew#2]
没消息推送的话登录失败了都不知道，不太方便。

**Comment by xhuanya** [comment]
好用兄弟我加邮箱提醒吧 毕竟不是每个人都一直上tg的

**Comment by xhuanya** [comment]
好兄弟我加邮箱提醒吧 毕竟不是每个人都一直上tg的
刚才打错字了从新回复一下

**Comment by ChirmyRam** [comment]
> 好兄弟我加邮箱提醒吧 毕竟不是每个人都一直上tg的
> 刚才打错字了从新回复一下

邮箱提醒也不错。

另外今天其他续期脚本都登录失败了，我发现德鸡官方登录入口加了验证码登录，甚至还有算数验证码。虽然你这个项目目前看起来没什么问题，不过还是建议看一下德鸡的登录机制，看看有没有需要更新的。

**Comment by xhuanya** [comment]
放心我这个是他官网看api文档写的 应该不会出啥大问题 好久没用golang的我得康康咋用的来着

**Comment by xhuanya** [comment]
以增加邮箱服务 问题关闭
